### ISSUE TITLE
在第六条数据快速向左滑动就会崩溃，或加载大量数据就会崩溃

### ISSUE THREAD

**Issue by wds1993225** [YiChaoLove/CoverFlow#3]
1，在加载第六条数据时，快速向左滑动(大约是第四个数据)，程序会报空指针异常
2，在加载大量数据时，快速滑动直接崩溃

**Comment by YiChaoLove** [comment]
抱歉，回复晚了，可能是你的调用方式存在问题，我测试没有发现问题，如有时间可否将异常贴出，谢谢

**Comment by wds1993225** [comment]
`839-1839/cn.wxhyi.coverflow E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.NullPointerException
                                                                      at cn.wxhyi.coverflow.CoverFlowView$CoverFlowScrollListener.onScrollStateChanged(CoverFlowView.java:215)
                                                                      at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:3740)
                                                                      at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1182)
                                                                      at android.support.v7.widget.RecyclerView.access$3700(RecyclerView.java:144)
                                                                      at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3874)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:531)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                                      at android.os.Handler.handleCallback(Handler.java:730)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                      at dalvik.system.NativeStart.main(Native Method)`
####你写的这个控件很赞
####这个问题在左右快速滑动的时候会出现，使用的是4.3的模拟器
